# Generated by Django 2.2.8 on 2020-02-10 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200207_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='trusted_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker', to=settings.AUTH_USER_MODEL),
        ),
    ]
