# Generated by Django 2.2.8 on 2020-02-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200210_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplyee',
            name='card',
            field=models.ImageField(blank=True, null=True, upload_to='static_in_env'),
        ),
    ]
