# Generated by Django 2.2.8 on 2020-02-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emplyee_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplyee',
            name='card',
        ),
        migrations.AddField(
            model_name='emplyee',
            name='card_id',
            field=models.CharField(default='F56OAvwJDVn7InkDB2RtXefc8kge3em1GMXISrg1xYmqhIKvvoMKwrMb_hL7j_WWp67_QQTtgqcKKf6PRhRnuvQU6K2ofPwz3JLbZ-MuFxS2n7wdbGtFDQs3Jb3-JJt-0S92hg', max_length=255),
        ),
    ]
