# Generated by Django 2.2.8 on 2020-02-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200212_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enter',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emplyee',
            name='card_id',
            field=models.CharField(default='m8t49WFLMlH6APAobWJsOiTWj-k', max_length=255),
        ),
    ]
