# Generated by Django 2.2.8 on 2020-02-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200214_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplyee',
            name='card_id',
            field=models.CharField(default='LqezOKnDU-eVjw', max_length=255),
        ),
    ]
