# Generated by Django 2.2.8 on 2020-02-15 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200214_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplyee',
            name='card_id',
            field=models.CharField(default='OvuXYY64BLpStQ', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 15, 13, 33, 59, 613913)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 15, 13, 33, 59, 613913)),
        ),
    ]
